<<<<<<< HEAD
epoch: 72

LearningRate:
  base_lr: 0.0001
=======
epoch: 300

LearningRate:
  base_lr: 0.00005
>>>>>>> f71c67ad701c1347be42e85b11e6cf040711b4b2
  schedulers:
  - !PiecewiseDecay
    gamma: 1.0
    milestones: [100]
    use_warmup: true
  - !LinearWarmup
    start_factor: 0.001
    steps: 2000

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
