metric: COCO
num_classes: 20

TrainDataset:
  name: COCODataSet
  image_dir: instances_train2017_images_640_025
  anno_path: instances_train2017_640_025.json
  dataset_dir: ../guangdong/coco_sliced
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: instances_val2017_images_640_025
  anno_path: instances_val2017_640_025.json
  dataset_dir: ../guangdong/coco_sliced
  allow_empty: true

# TestDataset:
#   name: ImageFolder
#   anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
#   dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'
